Update oxygen-deployment-1000032904.yml

diff --git a/.github/workflows/oxygen-deployment-1000032904.yml b/.github/workflows/oxygen-deployment-1000032904.yml
--- a/.github/workflows/oxygen-deployment-1000032904.yml
+++ b/.github/workflows/oxygen-deployment-1000032904.yml
@@ -11,7 +11,8 @@ jobs:
     timeout-minutes: 30
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Setup node.js
         uses: actions/setup-node@v4
@@ -34,6 +35,17 @@ jobs:
 
       - name: Install dependencies
         run: npm ci
+
+      - name: Fix vulnerabilities
+        run: |
+          npm audit fix || echo "Unable to fix all vulnerabilities."
+          npm audit fix --force || echo "Force fixes applied where possible."
+
+      - name: Run lint checks
+        run: npm run lint
+
+      - name: Run tests
+        run: npm test
 
       - name: Build and Publish to Oxygen
         run: npx shopify hydrogen deploy
